CUDA_VISIBLE_DEVICES=1 /home/lr/zym/.pyenv/versions/anaconda3-2023.09-0/envs/protein2rna/bin/python inference_model.py \
    --dataset_path /raid_elmo/home/lr/zym/protein2rna/ncbi_dataset/data/GCF/ \
    --output_dir /raid_elmo/home/lr/zym/protein2rna/results/Yeast_in_Ecoil \
    --esm_name_or_path "esm2_t12_35M_UR50D" \
    --model_path /raid_elmo/home/lr/zym/protein2rna/checkpoints/esm2_35M_5epoch/checkpoint-88000/pytorch_model.bin \
    --species_model "scibert" \
    --decoder_type "GenerRNA" \
    --GenerRNA_config_path /home/lr/zym/research/protein2rna/protein2rna/model/generRNA_config.json \
    --GenerRNA_tokenizer_path /home/lr/zym/research/protein2rna/GenerRNA/tokenizer_bpe_1024 \
    --protein_file_path /home/lr/zym/research/protein2rna/GCF_000146045.2/protein.faa \
    --cds_file_path /home/lr/zym/research/protein2rna/GCF_000146045.2/cds_from_genomic.fna \
    --species_file_path /home/yzhang/research/pro2rna/data/filtered_bacteria_species_updated_final.csv \ 